version: '3.9'

services:
  pzserver:
    build: .
    container_name: zomboid
    restart: unless-stopped
    stdin_open: true
    tty: true

    # DNS for reliable GitHub/Bitbucket access
    dns:
      - 8.8.8.8
      - 8.8.4.4

    # Ports mapping
    ports:
      - '8766-8767:8766-8767/udp'
      - '16261-16278:16261-16278/udp'
      - '27015:27015'

    volumes:
      # Only server files are mounted persistently
      - /docker-volumes/project-zomboid/server-files:/home/linuxgsm/Zomboid

    environment:
      PZ_SERVER_NAME: "Adam&Friends"
      PZ_ADMIN_PASSWORD: "admin"
      PZ_SERVER_PASSWORD: "Greg"
      PZ_MAX_PLAYERS: "32"

    ulimits:
      nofile:
        soft: 65535
        hard: 65535
