version: '3.9'

services:
  pzserver:
    image: ghcr.io/gameservermanagers/gameserver:pz
    container_name: zomboid
    restart: unless-stopped
    network_mode: host   # PZ requires host networking for Steam
    stdin_open: true
    tty: true

    # Persistent storage for server files and configs
    volumes:
      - /docker-volumes/project-zomboid/data:/data

    environment:
      PZ_SERVER_NAME: "Adam&Friends"
      PZ_ADMIN_PASSWORD: "admin"
      PZ_SERVER_PASSWORD: "Greg"
      PZ_MAX_PLAYERS: "32"
      LGSM_CURL_OPTIONS: "--connect-timeout 30 --max-time 300"

    ulimits:
      nofile:
        soft: 65535
        hard: 65535
